services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: local-converter-backend
    ports:
      - "3001:3001"
    environment:
      - FRONT_ORIGIN=http://localhost:5173
      # Improve file-watching inside containers
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    volumes:
      # Live-edit the source
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      # Persist uploads/outputs across restarts
      - backend_uploads:/app/uploads
      - backend_outputs:/app/outputs
    # Dev command: install on first run, then watch
    command: >
      sh -c "npm install && npm run dev"
    # If you want to ensure it waits for network before starting:
    # restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5

volumes:
  backend_node_modules:
  backend_uploads:
  backend_outputs: